# Generated by Django 4.1 on 2022-09-16 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_tags(apps, schema_editor):
    Tag = apps.get_model('blog', 'Tag')
    Tag.objects.bulk_create([
        Tag(name="Python"),
        Tag(name="Ruby"),
        Tag(name="Rust"),
        Tag(name="PHP"),
        Tag(name="C#"),
        Tag(name="C"),
        Tag(name="Perl"),
        Tag(name="JavaScript"),
        Tag(name="TypeScript"),
        Tag(name="Lisp"),
        Tag(name="Java"),
        Tag(name="Kotlin"),
        Tag(name="C++"),
        Tag(name="Swift"),
        Tag(name="Go"),
        Tag(name="Julia"),
        Tag(name="R"),
        Tag(name="Fortran"),
    ])


def unpopulate_tags(apps, schema_editor):
    Tag = apps.get_model('blog', 'Tag')
    Tag.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Body Text')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='An Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='blog.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='annotation')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
        ),
        migrations.RunPython(populate_tags, reverse_code=unpopulate_tags),
    ]
