# Generated by Django 4.0.5 on 2022-08-31 21:48

from django.db import migrations


def populate_tags(apps, schema_editor):
    Tag = apps.get_model('blog', 'Tag')
    Tag.objects.bulk_create([
        Tag(name="Python"),
        Tag(name="Ruby"),
        Tag(name="Rust"),
        Tag(name="PHP"),
        Tag(name="C#"),
        Tag(name="C"),
        Tag(name="Perl"),
        Tag(name="JavaScript"),
        Tag(name="TypeScript"),
        Tag(name="Lisp"),
        Tag(name="Java"),
        Tag(name="Kotlin"),
        Tag(name="C++"),
        Tag(name="Swift"),
        Tag(name="Go"),
        Tag(name="Julia"),
        Tag(name="R"),
        Tag(name="Fortran"),
    ])


def unpopulate_tags(apps, schema_editor):
    Tag = apps.get_model('blog', 'Tag')
    Tag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_tags, reverse_code=unpopulate_tags),
    ]
