# Generated by Django 2.2.7 on 2019-12-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191212_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensoredComment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.comment',),
        ),
        migrations.AddField(
            model_name='comment',
            name='age',
            field=models.PositiveIntegerField(default=19),
            preserve_default=False,
        ),
    ]
